<a href="https://colab.research.google.com/github/hajonghyun/installPytorch_study/blob/main/1_torch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

## `torch.tensor` vs `np.array` 핵심 비교

AI 엔지니어링, 특히 딥러닝 학습 단계로 넘어갈 때 가장 명확하게 이해해야 하는 두 자료형의 차이점입니다.

### 1. 요약 표

| 비교 항목 | NumPy (`np.array`) | PyTorch (`torch.tensor`) |
| :--- | :--- | :--- |
| **주 용도** | 일반 수치 계산, 데이터 전처리, 머신러닝(Scikit-learn) | **딥러닝 모델 학습**, GPU 가속 연산 |
| **하드웨어** | **CPU** 연산만 가능 | **CPU + GPU** 연산 지원 (`.to('cuda')`) |
| **미분(Gradient)** | 지원 안 함 (수식 직접 구현 필요) | **Autograd** (자동 미분) 지원 (`requires_grad=True`) |
| **메모리 공유** | `from_numpy()` 사용 시 메모리 공유 가능 | `torch.as_tensor()` 등으로 효율적 변환 가능 |

---

### 2. 주요 차이점 상세

#### A. GPU 가속 (Hardware Acceleration)
**가장 큰 차이점**입니다. NumPy는 CPU에서만 작동하지만, Tensor는 GPU로 데이터를 옮겨 대규모 병렬 연산(행렬 곱 등)을 빠르게 처리할 수 있습니다.

```python
import torch
import numpy as np

# NumPy: 오직 CPU 메모리 사용
arr = np.array([1, 2, 3])

# PyTorch: GPU로 이동 가능
tensor = torch.tensor([1, 2, 3])
if torch.cuda.is_available():
    tensor = tensor.to('cuda') # 데이터를 GPU VRAM에 올림
```

#### B. 자동 미분 (Autograd)
딥러닝의 핵심인 **역전파(Backpropagation)**를 수행하기 위해, PyTorch Tensor는 연산의 히스토리를 추적하고 미분값을 저장할 수 있습니다.

```python
# requires_grad=True: 이 텐서에 대한 연산을 추적하겠다는 의미
w = torch.tensor(2.0, requires_grad=True)

y = w ** 2      # 수식: y = w^2
y.backward()    # 미분 수행 (dy/dw)

print(w.grad)   # 결과: 4.0 (2 * w)
```
* **NumPy**는 단순히 값을 저장하고 계산할 뿐, 미분 계수(`grad`)를 자동으로 계산해주지 않습니다.

### 3. 결론 (AI 엔지니어 관점)
* **데이터 전처리/분석 단계:** `np.array`와 Pandas를 주로 사용합니다.
* **모델 학습/추론 단계:** 데이터를 `torch.tensor`로 변환하여 GPU에 올리고 모델에 주입합니다.

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

## `type()` vs `.dtype` 차이점 정리

파이썬으로 데이터 사이언스나 딥러닝을 할 때, **디버깅(에러 해결)의 80%는 이 두 가지를 구분하는 것**에서 시작됩니다.

### 1. 핵심 요약

| 구분 | 명령어 예시 | 설명 | 비유 (컵과 내용물) |
| :--- | :--- | :--- | :--- |
| **`type()`** | `type(data)` | **객체(컨테이너) 자체의 자료형**을 확인합니다.<br>(예: 이것은 리스트인가? 텐서인가?) | **"이 컵은 유리컵인가, 머그컵인가?"** |
| **`.dtype`** | `data.dtype` | **객체 안에 담긴 데이터(원소)의 자료형**을 확인합니다.<br>(예: 텐서 안에 들어있는 숫자가 `int`인가 `float`인가?) | **"컵 안에 든 것이 물인가, 콜라인가?"** |

---

### 2. 코드 예시 (PyTorch & NumPy)

가장 흔히 혼동하는 상황을 코드로 확인해 보세요.

```python
import torch
import numpy as np

# 데이터 생성
np_arr = np.array([1.0, 2.0, 3.0])
torch_tensor = torch.tensor([1, 2, 3]) # 정수로 생성

# 1. type(): 껍데기 확인
print(type(np_arr))       # <class 'numpy.ndarray'> -> "이것은 넘파이 배열입니다."
print(type(torch_tensor)) # <class 'torch.Tensor'>  -> "이것은 파이토치 텐서입니다."

# 2. .dtype: 내용물 확인 (매우 중요!)
print(np_arr.dtype)       # float64 -> "안에 실수가 들어있습니다."
print(torch_tensor.dtype) # torch.int64 -> "안에 정수가 들어있습니다."
```

### 3. 왜 중요한가요? (AI 엔지니어 관점)

* **`type()` 에러:** 주로 **호환성** 문제입니다.
    * *예: PyTorch 모델에 실수로 NumPy 배열을 넣으면 `TypeError`가 발생합니다.*
* **`.dtype` 에러:** 주로 **정밀도나 연산** 문제입니다.
    * *예: 딥러닝 모델 가중치는 보통 `float32`인데, 입력 데이터가 `int64`나 `float64`면 `RuntimeError: expected scalar type Float but found Double` 같은 에러가 뜹니다.*
    * **해결:** `tensor.to(torch.float32)` 처럼 캐스팅(형변환)을 해줘야 합니다.

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([1.0, 2, 3]) # 하나라도 실수면 dtype은 float

In [ ]:
print(type(a), type(b))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [ ]:
print(a.dtype, b.dtype)

torch.int64 torch.float32


In [ ]:
print(a.shape)

torch.Size([3])


## Tensor 핵심 속성 및 형태 규칙

### 1. 형태 규칙 (Shape Constraint)
* **직사각형 형태 강제 (Strict Rectangular):** Tensor는 GPU 병렬 연산을 위해 모든 행(Row)의 길이가 반드시 같아야 합니다.
    * `[[1, 2, 3], [4, 5]]` ❌ : **Jagged Tensor 불가** (에러 발생)
    * `[[1, 2, 3], [4, 5, 6]]` ⭕ : 생성 가능

### 2. 필수 속성 조회 3대장

딥러닝 모델 디버깅 시 `print()`로 가장 많이 찍어보는 3가지입니다.

```python
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# 1. 모양 (Shape) - ★가장 중요★
# 각 차원의 크기를 확인 (행, 열)
print(a.shape)    # torch.Size([2, 3])

# 2. 차원 수 (Dimension/Rank)
# 몇 차원 텐서인지 확인
print(a.ndim)     # 2

# 3. 전체 원소 개수 (Number of Elements)
# 2행 * 3열 = 총 6개
print(a.numel())  # 6
```

In [ ]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
# b = torch.tensor([[1,2,3],
#                   [4,5]])
# np.array와는 달리 torch.tensor는 행렬
# 각 행에 해당하는 숫자의 개수 같아야함.

print(a.shape)
print(a.ndim) # 차원 수
print(a.numel()) # num of element 요소의 수

torch.Size([2, 3])
2
6


## Tensor 생성 및 초기화 (NumPy와 비교)

PyTorch는 NumPy와 매우 유사한 API를 제공하지만, **Shape 입력 방식**에서 더 유연합니다.

### 1. 0 또는 1로 채우기 (`zeros`, `ones`)
* **핵심 차이:** `torch`는 차원(Shape)을 튜플 `()`로 묶지 않고 **인자로 바로 나열**해도 됩니다. (NumPy는 튜플 필수)

```python
# 5행 5열 0행렬
print(torch.zeros(5, 5))  # OK: 괄호 하나로 충분
# print(np.zeros(5, 5))   # Error: np.zeros((5, 5))여야 함

# 2행 2열 1행렬
print(torch.ones(2, 2))
```

### 2. 형태 복제하기 (`_like`)
* 기존 텐서 `a`의 **Shape(모양), Dtype(자료형), Device(CPU/GPU)** 속성을 그대로 물려받아 새로운 텐서를 만듭니다.

```python
# a와 똑같은 모양으로 0을 채움
print(torch.zeros_like(a))
```

### 3. 수열 생성 (`arange`, `linspace`)
* 데이터 인덱싱이나 그래프 축(x-axis)을 만들 때 주로 사용합니다.

| 함수 | 설명 | 인자 의미 | 예시 |
| :--- | :--- | :--- | :--- |
| **`arange`** | 간격(Step) 기준 생성 | `(시작, 끝, 간격)` | `torch.arange(0, 10, 2)`<br>→ `[0, 2, 4, 6, 8]` (끝 미포함) |
| **`linspace`** | 개수(Count) 기준 생성 | `(시작, 끝, 개수)` | `torch.linspace(0, 10, 5)`<br>→ `[0, 2.5, 5, 7.5, 10]` (끝 포함) |

In [ ]:
print(torch.zeros(5,5))
print(np.zeros((5,5)))

print('\n')

print(torch.zeros_like(a))
print(np.zeros_like(a))

print('\n')

print(torch.ones(2,2))
print(np.ones((2,2)))

print('\n')

print(torch.arange(3,10,2))
print(np.arange(3,10,2))

print('\n')

print(torch.linspace(1,10,10))
print(np.linspace(1,10,10))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


tensor([[0, 0, 0],
        [0, 0, 0]])
[[0 0 0]
 [0 0 0]]


tensor([[1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]]


tensor([3, 5, 7, 9])
[3 5 7 9]


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


## Tensor 기본 연산 (Element-wise vs Dot Product)

PyTorch 연산에서 가장 중요한 것은 **`*` (단순 곱)**과 **`@` (행렬 곱)**을 구분하는 것입니다.

### 1. 원소별 연산 (Element-wise)
기본 산술 연산자(`+`, `-`, `*`, `/`, `**`)는 **같은 위치(Index)에 있는 원소끼리** 1:1로 계산합니다. 결과의 모양(Shape)이 유지됩니다.

```python
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 2, 1])

# [1*3, 2*2, 3*1]
print(a * b)   # tensor([3, 4, 3]) -> 이를 아다마르 곱(Hadamard Product)이라고도 함

# [1^2, 2^2, 3^2]
print(a ** 2)  # tensor([1, 4, 9])
```

### 2. 내적 / 행렬 곱 (Dot Product)
**`@` 연산자**는 벡터의 내적(Inner Product) 또는 행렬 곱셈을 수행합니다. 1차원 벡터끼리 연산하면 결과가 하나의 값(Scalar)으로 합쳐집니다.

```python
# 계산 과정: (1*3) + (2*2) + (3*1) = 3 + 4 + 3 = 10
print(a @ b)   # tensor(10)
```

> **Tip:** 과거에는 `torch.matmul(a, b)`를 많이 썼지만, 최신 코드에서는 가독성을 위해 **`a @ b`**를 더 선호합니다.

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([3,2,1])
print(a+b)
print(a*b) #
print(a@b) #

print(a/b)
print(a**2)  # 제곱도 각 성분에 대해서.

tensor([4, 4, 4])
tensor([3, 4, 3])
tensor(10)
tensor([0.3333, 1.0000, 3.0000])
tensor([1, 4, 9])


## pytorch의 인덱싱과 슬라이싱
--> numpy, list와 똑같음.

In [62]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])

print(a[7:])
print(a[2:5])
print(a[::2])
print(a[:])

tensor([8, 9])
tensor([3, 4, 5])
tensor([1, 3, 5, 7, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [69]:
a = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(a[0])
print(a[-1])
print(a[1:])
print(a[:])
print(a[0][2])
print(a[0,2])   # 일반 list에서는 불가! np, torch에서만 가능

print(a[:][2]) # a[:] == a
print(a[:,2]) # 위와 결과가 다름을 알 수 있음.


tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([7, 8, 9])
tensor([3, 6, 9])


## 3차원 텐서와 차원(Shape) 규칙

### 1. 3차원 텐서 구조 해석 (`2, 3, 4`)
텐서의 Shape은 **가장 바깥쪽 대괄호부터 안쪽으로** 파고들며 해석합니다.

* `torch.Size([2, 3, 4])`
    * **2 (Depth):** 큰 덩어리(면)가 2개
    * **3 (Row):** 각 덩어리 안에 행이 3개
    * **4 (Col):** 각 행 안에 열(원소)이 4개

### 2. 대괄호와 차원의 관계 (The Bracket Rule)
**"대괄호 `[]`를 한 겹 씌울 때마다, Shape의 맨 왼쪽에 `1`이 추가됩니다."**

내용물(데이터)은 같아도, 대괄호로 감싸면 **차원(Rank)**이 높아집니다.

```python
import torch

# 1. 기본: 1차원 벡터 (요소 4개)
a = torch.tensor([1, 2, 3, 4])
print(a.shape) # torch.Size([4])

# 2. 대괄호 1겹 추가 -> 2차원 (1행 4열)
b = torch.tensor([[1, 2, 3, 4]])
print(b.shape) # torch.Size([1, 4])

# 3. 대괄호 2겹 추가 -> 3차원 (덩어리 1개, 1행 4열)
c = torch.tensor([[[1, 2, 3, 4]]])
print(c.shape) # torch.Size([1, 1, 4])

# 4. 대괄호 3겹 추가 -> 4차원
d = torch.tensor([[[[1, 2, 3, 4]]]])
print(d.shape) # torch.Size([1, 1, 1, 4])
```

> **Tip:** 이렇게 `1`인 차원이 불필요하게 생겼을 때는 **`squeeze()`** 함수로 제거할 수 있습니다.

In [71]:
# 3차원 행렬 인덱싱
a = torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                  [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(a)
print(a.shape)
print(a.ndim)


# 대괄호가 하나 늘어나면 왼쪽에 shape값이 추가된다.
a = torch.tensor([[1,2,3,4]])
print(a.shape)

a = torch.tensor([[[1,2,3,4]]])
print(a.shape)

a = torch.tensor([[[[1,2,3,4]]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
3
torch.Size([1, 4])
torch.Size([1, 1, 4])
torch.Size([1, 1, 1, 4])


## PyTorch 팬시 인덱싱 (Fancy Indexing)

슬라이싱(`:`)이 범위를 칼로 자르는 것이라면, 팬시 인덱싱은 **원하는 지점만 콕콕 집어내거나(Picking)** 순서를 내 마음대로 섞는 기법입니다.

## 1. 판단 기준: "이게 팬시 인덱싱인가?"
대괄호 `[]` 안에 **숫자 하나**나 **슬라이싱(`:`)**이 아닌, **또 다른 리스트(List)나 배열(Tensor)**이 들어가 있다면 팬시 인덱싱입니다.

* `a[1:3]` : 슬라이싱 (범위)
* `a[[1, 3]]` : **팬시 인덱싱** (1번과 3번만 선택)

---

## 2. 핵심 해석법: "메인 콤마(,)의 법칙" ★★★
복잡한 대괄호 속에서 길을 잃지 않는 유일한 법칙입니다. **가장 바깥쪽 콤마**가 차원을 가르는 국경선입니다.

### Case A. 콤마가 있다? -> `a[ [0,1], [0,1] ]`
* **의미:** 차원별로 좌표를 따로 줬다는 뜻입니다.
* **해석법:** **"좌표 찍기 (Zipping)"**
    * 리스트들을 세로로 나란히 놓고 같은 순서끼리 묶어서 $(x, y)$ 좌표를 만듭니다.
    * 예: `(0,0)` 좌표의 값 하나, `(1,1)` 좌표의 값 하나.

### Case B. 콤마가 없다? -> `a[ [0,1] ]`
* **의미:** 리스트 전체가 **첫 번째 차원(Dim 0)**에 통째로 들어갔다는 뜻입니다.
* **해석법:** **"덩어리 선택 (Selection)"**
    * "0번 덩어리와 1번 덩어리를 통째로 가져와라."
    * 남은 차원은 건드리지 않았으므로 그대로 유지됩니다.

In [78]:
a = torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                  [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(a)
a[[0,1,1,0],[0,1,2,1],[3,3,2,1]]

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([ 3, 19, 22,  5])

### 팬시 인덱싱 점검: 4차원 텐서 퀴즈

제대로 이해했는지 확인하는 고난도 4차원 문제입니다.

### 기본 설정
0부터 15까지 숫자가 채워진 `(2, 2, 2, 2)` 텐서입니다.
```python
import torch
a = torch.arange(16).view(2, 2, 2, 2)
```



In [80]:
# shape: (2, 2, 2, 2) -> (B, C, H, W)라고 상상해보세요.
a = torch.arange(16).view(2, 2, 2, 2)

print(a)

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])


### Q1. 좌표 콕콕 찍기 (Basic)
리스트가 모든 차원에 다 들어간 경우입니다.
```python
# 힌트: 세로로 묶어서 좌표(0,0,0,0)과 (1,1,1,1)을 만드세요.
print(a[[0, 1], [0, 1], [0, 1], [0, 1]])
```
> **정답:** `tensor([0, 15])`
> **해설:** 점 2개를 핀셋으로 집어낸 결과이므로 1차원 벡터가 됩니다.

In [82]:
print(a[[0, 1], [0, 1], [0, 1], [0, 1]])

tensor([ 0, 15])


### Q2. 고정과 선택의 조화 (Intermediate)
앞쪽 차원은 숫자로 고정하고, 뒤쪽 차원만 리스트로 선택하는 경우입니다.
```python
# 힌트: 앞의 0, 1은 고정! 뒤의 [0,1], [1,0]만 짝을 지으세요.
print(a[0, 1, [0, 1], [1, 0]])
```
> **정답:** `tensor([5, 6])`
> **해설:**
> * 좌표 1: `(0, 1, 0, 1)` -> 값 5
> * 좌표 2: `(0, 1, 1, 0)` -> 값 6

In [83]:
print(a[0, 1, [0, 1], [1, 0]])

tensor([5, 6])


### Q3. 덩어리째 가져오기 (Advanced)
**메인 콤마가 없는** 경우입니다.
```python
# 힌트: [1, 1, 0] 리스트 전체가 Dim 0에 적용됩니다.
print(a[[1, 1, 0]].shape)
```
> **정답:** `torch.Size([3, 2, 2, 2])`
> **해설:**
> * Dim 0에서 1번, 1번, 0번 덩어리를 순서대로 가져왔으므로 개수가 **3개**가 됩니다.
> * 뒤쪽 차원 `(2, 2, 2)`는 건드리지 않았으므로 그대로 유지됩니다.

In [84]:
print(a[[1, 1, 0]].shape)

torch.Size([3, 2, 2, 2])
